GET http://localhost:3000/api/buses


###Buscar un bus por placa
GET http://localhost:3000/api/buses/search/ABC-1123
### Crear un bus
POST http://localhost:3000/api/buses
Content-Type: application/json

{
    "numero_bus": 1,
    "placa": "ABD-1123",
    "chasis": "Normal",
    "carroceria": "Sedan",
    "total_asientos_normales": 40,
    "total_asientos_vip": 10
}

###Eliminar un bus
DELETE http://localhost:3000/api/buses/13


###Actualizar un bus
PUT http://localhost:3000/api/buses/14
Content-Type: application/json

  {
    "numero_bus": 3,
    "placa": "ADC-1242",
    "chasis": "miperro",
    "carroceria": "Sedan2",
    "total_asientos_normales": 30,
    "total_asientos_vip": 20,
    "activo": true
  }