### Obtener todas las frecuencias
GET http://localhost:3000/api/frecuencias


###Obtener una frecuencia por ID
GET http://localhost:3000/api/frecuencias/8


###Obtener frecuencias por conductor
GET http://localhost:3000/api/frecuencias/conductor/18

###Obtener frecuencias por bus
GET http://localhost:3000/api/frecuencias/bus/14


###Obtener por canton (destino)
GET http://localhost:3000/api/frecuencias/destino/destino

###Obtener por provincia
GET http://localhost:3000/api/frecuencias/provincia/El Oro

###Obtener por canton (origen)
GET http://localhost:3000/api/frecuencias/origen/Ambato

### Crear una nueva frecuencia
POST http://localhost:3000/api/frecuencias
Content-Type: application/json

{
    "nombre_frecuencia": "Ambato - Riobamba",
    "bus_id": 2,
    "conductor_id": 1,
    "hora_salida": "18:30:00",
    "hora_llegada": "19:00:00",
    "origen": "Ambato",
    "destino": "Riobamba", 
    "provincia": "Chimborazo",
    "total": 10,
    "nro_aprobacion": "ANT-2024-001"
}


###Eliminar 
DELETE http://localhost:3000/api/frecuencias/7


###Actualizar
PUT http://localhost:3000/api/frecuencias/12
Content-Type: application/json

{
    "es_directo": false,
    "origen": "Ambato",
    "destino": "Quito",
    "provincia": "Pichincha"

}