###Obtener todas las paradas
GET http://localhost:3000/api/paradas


###Buscar parada por ciudad
GET http://localhost:3000/api/paradas/ciudad/Santo Domingo


###Buscar parada por like ciudad
GET http://localhost:3000/api/paradas/buscar/gu

###Crear una parada
POST http://localhost:3000/api/paradas
Content-Type: application/json

{
    "ciudad": "Latacunga"
}

###Actualizar una parada
PUT http://localhost:3000/api/paradas/19
Content-Type: application/json

{
    "ciudad": "  ssdsd "
}

###Eliminar una parada
DELETE http://localhost:3000/api/paradas/26